
version: '3.1'

services:

  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200

  kibana:
    image: kibana
    ports:
      - 5601:5601
  
  filebeat:
    build: ./filebeat

  logstash:
    build: ./logstash
    ports:
      - 5044:5044
